version: '2'

services:
  proxy:
    image: traefik
    command: --docker.domain=${DOMAIN} --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme/acme.json

  redis:
    image: "redis:3.2"
    command: "redis-server --appendonly yes"
    volumes:
      - "redis_data:/data"

  echo:
    build: ./echo
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:echo.${DOMAIN}"
      - "traefik.port=80"
    working_dir: "/usr/src/app"
    volumes:
      - "./:/usr/src/app"

volumes:
  redis_data:
