version: '2'

services:
  proxy:
    image: traefik
    command: --docker.domain='https://schoolbus-echo-xbdpujvn6q-no.a.run.app' --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme/acme.json

  redis:
    image: "redis"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"

  echo:
    build: ./echo
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:echo.'https://schoolbus-echo-xbdpujvn6q-no.a.run.app'"
      - "traefik.port=80"
    working_dir: "/usr/src/app"
    depends_on:
      - redis
    volumes:
      - "./:/usr/src/app"

networks:
  default:
    external:
      name: cloudbuild
